"""Initial schema

Revision ID: 728f30391506
Revises: 
Create Date: 2026-03-27 23:16:41.395893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728f30391506'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_id'), 'enterprise', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_name'), 'enterprise', ['name'], unique=True)
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('private_area_m2', sa.Float(), nullable=False),
    sa.Column('garage_code', sa.String(length=50), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('ideal_capture_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_code'), 'unit', ['code'], unique=False)
    op.create_index(op.f('ix_unit_enterprise_id'), 'unit', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_unit_id'), 'unit', ['id'], unique=False)
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(length=255), nullable=True),
    sa.Column('scenario_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payload_snapshot', sa.JSON(), nullable=False),
    sa.Column('pv_status', sa.String(length=50), nullable=True),
    sa.Column('capture_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_id'), 'proposal', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_unit_id'), 'proposal', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_unit_id'), table_name='proposal')
    op.drop_index(op.f('ix_proposal_id'), table_name='proposal')
    op.drop_table('proposal')
    op.drop_index(op.f('ix_unit_id'), table_name='unit')
    op.drop_index(op.f('ix_unit_enterprise_id'), table_name='unit')
    op.drop_index(op.f('ix_unit_code'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_enterprise_name'), table_name='enterprise')
    op.drop_index(op.f('ix_enterprise_id'), table_name='enterprise')
    op.drop_table('enterprise')
    # ### end Alembic commands ###
