"""Add enterprise and unit fields

Revision ID: 88ef11bb5381
Revises: 728f30391506
Create Date: 2026-03-28 12:21:42.116598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ef11bb5381'
down_revision: Union[str, Sequence[str], None] = '728f30391506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('work_code', sa.String(length=50), nullable=True))
    op.add_column('enterprise', sa.Column('spe_name', sa.String(length=255), nullable=True))
    op.add_column('enterprise', sa.Column('vpl_rate_annual', sa.Float(), nullable=False))
    op.add_column('enterprise', sa.Column('discount_percent', sa.Float(), nullable=False))
    op.add_column('enterprise', sa.Column('delivery_month', sa.String(length=20), nullable=True))
    op.add_column('enterprise', sa.Column('launch_date', sa.String(length=20), nullable=True))
    op.add_column('enterprise', sa.Column('stage', sa.String(length=100), nullable=True))
    op.add_column('unit', sa.Column('product_unit_key', sa.String(length=255), nullable=True))
    op.add_column('unit', sa.Column('unit_type', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('suites', sa.Integer(), nullable=True))
    op.add_column('unit', sa.Column('garage_spots', sa.Integer(), nullable=True))
    op.add_column('unit', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_unit_product_unit_key'), 'unit', ['product_unit_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_product_unit_key'), table_name='unit')
    op.drop_column('unit', 'status')
    op.drop_column('unit', 'garage_spots')
    op.drop_column('unit', 'suites')
    op.drop_column('unit', 'unit_type')
    op.drop_column('unit', 'product_unit_key')
    op.drop_column('enterprise', 'stage')
    op.drop_column('enterprise', 'launch_date')
    op.drop_column('enterprise', 'delivery_month')
    op.drop_column('enterprise', 'discount_percent')
    op.drop_column('enterprise', 'vpl_rate_annual')
    op.drop_column('enterprise', 'spe_name')
    op.drop_column('enterprise', 'work_code')
    # ### end Alembic commands ###
