"""Add global parameters table

Revision ID: e0ada32428da
Revises: 88ef11bb5381
Create Date: 2026-03-29 18:11:44.028082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ada32428da'
down_revision: Union[str, Sequence[str], None] = '88ef11bb5381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalparameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_globalparameter_id'), 'globalparameter', ['id'], unique=False)
    op.create_index(op.f('ix_globalparameter_key'), 'globalparameter', ['key'], unique=True)
    # ### end Alembic commands ###

    # Seed initial data
    op.execute(
        "INSERT INTO globalparameter (key, value, description) VALUES ('vpl_rate_annual', 0.1003, 'Taxa de desconto (VPL) padrão do sistema')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_globalparameter_key'), table_name='globalparameter')
    op.drop_index(op.f('ix_globalparameter_id'), table_name='globalparameter')
    op.drop_table('globalparameter')
    # ### end Alembic commands ###
